__version__ = "1.0.0"

model = "vehicle3dof1"

[simulink]
    solver = "FixedStepAuto"
    absolute_time = false
    integer_code = false
    non_finite = false
    complex = false
    continuous_time = true
    variable_size_signal = true
    non_inlined_sfcn = false

[cpp]
    class_name = "Veh3dofconti"
    namespace = ""

[info]
    description = "<auto>"
    version = "<auto>"
    author = "<auto>"
    license = "<no-license>"
