name: gops

channels:
  - defaults

dependencies:
  - python=3.8
  - numpy>1.16.0
  - ray-default>=1.0.0
  - pandas
  - tensorboard>=2.5.0
  - matplotlib
  - seaborn
  - scipy
  - pip
  - pip:
    # PyTorch packages with CUDA 12.1 support
    - torch==2.3.1
    - torchvision==0.18.1
    - torchaudio==2.3.1
    - gym==0.23.1
    - gymnasium==0.29.1
    - box2d
    - pygame
    - pyglet
    - slxpy
    - openpyxl
    - pytest
    - onnx==1.16.0 
    - onnxruntime==1.18.1
